# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Environment
      run: docker version
    - name: Install Bats
      run: sudo apt install bats
    - name: Pull Docker Image
      run: docker pull wechaty/wechaty
    - name: Test
      run: |
          pwd
          ls -l
          ./bin/docker-run.sh tests/fixtures/javascript.js
          bats tests/
